service: serverless-app-boilerplate

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs14.x
  stage: ${opt:stage, 'stage'}
  environment: ${file(./env/${self:provider.stage}.yml)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 5

package:
  artifact: dst.zip

functions:
  api:
    timeout: 30
    memorySize: 256
    handler: api.handler
    events:
      - http:
          path: /{proxy+}
          method: any
