service: serverless-app-boilerplate

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs12.x
  stage: ${opt:stage, 'stage'}
  environment: ${file(./env/${self:provider.stage}.yml)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 5

package:
  artifact: dst.zip

functions:
  api:
    timeout: 30
    memorySize: 256
    handler: api.handler
    events:
      - http:
          path: /{proxy+}
          method: any

resources:
  Resources:
    TodoListTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # Align below properties with src/models/todo_list.ts
        TableName: ${self:provider.stage}_todo_list
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    TodoListItem:
      Type: AWS::DynamoDB::Table
      Properties:
        # Align below properties with src/models/todo_item.ts
        TableName: ${self:provider.stage}_todo_item
        AttributeDefinitions:
          - AttributeName: listId
            AttributeType: S
          - AttributeName: itemId
            AttributeType: S
        KeySchema:
          - AttributeName: listId
            KeyType: HASH
          - AttributeName: itemId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
